transfer_file

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,20 +1,22 @@
 #!/usr/bin/env bash
-# Transfers a file from our clients to a server
+# Check if all 4 parameters are passed
+if [ $# -ne 4 ]; then
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
 
-file_path_to_be_transferred=$1
-ip=$2
+# Assign parameters to variables
+file_path=$1
+server_ip=$2
 username=$3
-path_to_private_key=$4
+ssh_key=$4
 
-i=0;
-for _ in "$@"
-do
-	i=$((i + 1));
-done
+# Transfer file to server using scp
+scp -o StrictHostKeyChecking=no -i $ssh_key $file_path $username@$server_ip:~/
 
-if [ $i == 4 ]
-then
-	scp -o StrictHostKEyChecking=no -i "$path_to_private_key" "$file_path_to_be_transferred" "$username"@"$ip":~/
+# Check if the file transfer was successful
+if [ $? -eq 0 ]; then
+  echo "File transfer successful!"
 else
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
+  echo "File transfer failed."
 fi
