not_found_page_404

diff --git a/0x0C-web_server/4-not_found_page_404 b/0x0C-web_server/4-not_found_page_404
--- a/0x0C-web_server/4-not_found_page_404
+++ b/0x0C-web_server/4-not_found_page_404
@@ -1,32 +1,29 @@
 #!/usr/bin/env bash
-# Install nginx on your web server if it is not already installed
+# Install nginx on your web-01
+# Check if Nginx is installed
+if ! command -v nginx &> /dev/null; then
+    # Update package lists and install Nginx
+    sudo apt-get update
+    sudo apt-get install -y nginx
+fi
 
-sudo apt update
-sudo apt install -y nginx
+# Configure Nginx to listen on port 80
+sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
 
-# Create a custom 404 error page
-echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
+# Check if the custom index.html file exists
+if [ ! -f /var/www/html/index.html ]; then
+    # Create a custom index.html file with the "Hello World!" content
+    echo "Hello World!" | sudo tee /var/www/html/index.html
+fi
 
-# Configure Nginx to use the custom 404 error page
-sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/default
-server {
-    listen 80 default_server;
-    listen [::]:80 default_server;
-    server_name 18.207.2.134;
-    root /var/www/html;
-    index index.html;
-    location / {
-        try_files $uri $uri/ =404;
-    }
-    error_page 404 /custom_404.html;
-    location = /custom_404.html {
-        internal;
-        add_header Content-Type text/html;
-        add_header ETag "58acb50e-1a";
-        root /var/www/html;
-    }
-}
-EOF'
+# Set up /redirect_me to a YouTube video if it doesn't exist
+if ! sudo grep -q "location \/redirect_me" /etc/nginx/sites-available/default; then
+    sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
+fi
 
-# Restart Nginx
-sudo service nginx restart
+# Set up a 404 page
+echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
+sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-available/default
+
+# Restart Nginx without using systemctl
+sudo nginx -t && sudo service nginx restart
